### ISSUE TITLE
Move methods depending on OpenSSL to the corresponding package

### ISSUE THREAD

**Issue by mtabacman** [ba-st-dependencies/JSONWebToken#7]
String extensions asPrivateKey and asPublicKey are implemented in the package JSONWebToken-Pharo-Core
They depend on classes LcEvpPublicKey and LcRSA, which are only available if the OpenSSL baseline is loaded
When only using the Core baseline for JSONWebToken, these methods are not required, and are currently generating a loading error because those classes are not available.
Both extension methods should be moved to the JSONWebToken-OpenSSL package.

**Comment by gcotelli** [comment]
We need to be careful to not break the GS64 components
